### ISSUE TITLE
Use fringe instead of margins

### ISSUE THREAD

**Issue by wyuenho** [rnkn/olivetti#19]
If you pad the windows with fringes like https://github.com/anler/centered-window-mode, will it fix the incompatibility with `linum` and `display-line-numbers-mode`?

**Comment by rnkn** [comment]
I’m pretty sure `linum-mode` is fixed in 26.1.

Sorry to say, but issues with `display-line-numbers-mode` are due to the lack of foresight/consideration from its creator/maintainer. I’ve had a very frustrating time dealing with him, so please report its bugs to bug-gnu-emacs@gnu.org

I’m not sure if this is related to using fringes but it seems `centered-window-mode` has run into the same show-stopper I did when Emacs 25.1 was released: https://github.com/anler/centered-window-mode/issues/12

**Comment by rnkn** [comment]
p.s. Also fringes only work on graphical displays.

**Comment by rnkn** [comment]
I was wrong about the incompatibility with `display-line-numbers-mode`. An update is forthcoming.

**Comment by sten0** [comment]
I'm curious about that update :-)  On my end, I haven't yet tested Olivetti 1.8.0, but 1.6.1 seems to work fine with `display-line-numbers-mode` (on Debian 10 with Emacs 26.1).  The only oddity I could see is that pressing return to go to a new line does not create a new line number until something else is inputted--either text or another new line.

**Comment by rnkn** [comment]
I tried working with the author of display-line-numbers-mode quite a bit to make it fully compatible, but unfortunately there was just no give on the other side.
