### ISSUE TITLE
Incompatibility with diff-hl and making olivetti a global mode

### ISSUE THREAD

**Issue by walseb** [rnkn/olivetti#42]
Hi! This config used to work a few commits ago:
```
(eval-and-compile
  (defvar bootstrap-version)
  (let ((bootstrap-file
	 (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
	(bootstrap-version 5))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
	  (url-retrieve-synchronously
	   "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
	   'silent 'inhibit-cookies)
	(goto-char (point-max))
	(eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage)))

(straight-use-package 'diff-hl)
(global-diff-hl-mode)

(straight-use-package 'olivetti)
(define-globalized-minor-mode global-olivetti-mode
  nil (lambda ()
	(pcase major-mode
	  ('minibuffer-inactive-mode)
	  ('exwm-mode)
	  ('mu4e-headers-mode)
	  ('pdf-view-mode)
	  ('image-mode)
	  (_ (olivetti-mode 1)))))
(global-olivetti-mode 1)
```
(load it with `emacs -Q -l NAME-OF-CONFIG.el`)
but now if you run it, open a file under git version control, make a change and then save, olivetti stops working until you change the window size among other things. Maybe there is a better way to make `olivetti-mode` global that doesn't introduce this bug? Thanks for making this package!

**Comment by rnkn** [comment]
Please attempt to reproduce this with `emacs -Q` and `M-x load-file RET [PATH TO FILE]`

**Comment by walseb** [comment]
Do you mean something like this?
```
M-x load-file RET diff-hl.el RET
M-x load-file RET olivetti.el RET
M-x eval-expression RET (global-diff-hl-mode)
                        (define-globalized-minor-mode global-olivetti-mode
                          nil (lambda ()
                                (pcase major-mode
                                  ('minibuffer-inactive-mode)
                                  ('exwm-mode)
                                  ('mu4e-headers-mode)
                                  ('pdf-view-mode)
                                  ('image-mode)
                                  (_ (olivetti-mode 1)))))
                        (global-olivetti-mode 1)
M-x eval-expression RET (find-file "/file/under/git/vc")
M-x eval-expression RET (insert "test")
M-x save-buffer RET
```

**Comment by rnkn** [comment]
No I mean just loading olivetti.el and attempting to reproduce your issue without additional code.

**Comment by larstvei** [comment]
Hi!

I use diff-hl and tried your globalized mode, and don't experience the problems you report.

However, I did experience similar issues when using git-gutter-fringe, which is a diff-hl equivalent I used before. diff-hl resolved it for me though. It is not particularly surprising if there are incompatibilities between packages that "mess with" the margins of the buffer.

Because I'm not able to reproduce it with the same combination of packages, there are a couple of things you could try. See if there is any additional package or configuration that might be the culprit; you can check this by starting Emacs with `emacs -Q` as @rnkn suggests (which inhibits your emacs config file to be loaded), and then follow the steps you suggested yourself @walseb. If the error persists, then make sure you have updated versions of both packages. Maybe check if you are using the melpa stable version of olivetti (I would suggest trying the non-stable).

**Comment by walseb** [comment]
@rnkn No additional code at all? Because then it's not possible, it only happens when I define a `globalized-minor-mode` for it. I am running all the code above in a `emacs -Q` instance without any code not mentioned here if that's what you mean.

@larstvei Yeah, that's what I'm doing. I just run `emacs -Q -l configIProvidedAbove.el`. I'm using the latest version of olivetti published yesterday (`fa9757f`) and the latest version of `diff-hl` (`a625033`)

I'm running `GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.10)`. And actually it appears as if the bug only happens after saving and editing for the second time. I'm not sure if that's due to the latest commits, but it does happen consistently using the config above on my pc with `emacs -Q`.

**Comment by larstvei** [comment]
Okay, thanks. I was confused by the straight.el stuff, and thought that was downloading your config.

I'm able to reproduce it now. This is only when using the globalized mode and along with diff-hl mode. This being a user-defined globalized mode not working properly with another (not built-in) package, I don't think this is an olivetti bug.

I'll try to debug this a little, but I'm guessing that an eventual fix will be in the globalized mode.

**Comment by larstvei** [comment]
I just added some debugging prints in the lambda, checking what major modes and buffers were invoked. Turnes out diff-hl creates a buffer, which causes problems.

Does this fix your issue?

```elisp
(define-globalized-minor-mode global-olivetti-mode
  nil (lambda ()
        (unless (string= " *diff-hl* " (buffer-name (current-buffer)))
          (pcase major-mode
            ('minibuffer-inactive-mode)
            ('exwm-mode)
            ('mu4e-headers-mode)
            ('pdf-view-mode)
            ('image-mode)
            (_ (olivetti-mode 1))))))
```

**Comment by walseb** [comment]
Yeah that works, thanks a lot!

**Comment by rnkn** [comment]
If there was an incompatibility with a mode that is part of Emacs I would investigate further, but I’m unfamiliar with diff-hl so I can’t help you there sorry.

If Lars is familiar with the modes you’re using and if this sparks his interest he might be able to shed more light.

We recently needed to make use of the min-margins window parameter to work around some longstanding issues with window display so that could be a clue.

**Comment by rnkn** [comment]
Sorry, obviously I'm lagging behind here. Glad to see you got it sorted. Thanks @larstvei :)
