### ISSUE TITLE
hide menu bars, toggle fullscreen

### ISSUE THREAD

**Issue by anarcat** [rnkn/olivetti#6]
it would be great if olivetti could turn off menu bars and turn on full screen. i tried to suggest (and implement) this in darkroom, a similar mode, but failed to both implement it properly and get the concept accepted: https://github.com/capitaomorte/darkroom/pull/2 i'd be curious to see if there would be more interest here.

**Comment by rnkn** [comment]
I had a look at the linked issue and echo the same reasoning made there. The menu bar and fullscreen are both specific to the frame rather than the buffer. Keeping everything buffer-local was my main reason for making olivetti rather than using one of the similar existing modes.

You should check out [writeroom-mode](https://github.com/joostkremers/writeroom-mode), which I think does what you're after.

**Comment by anarcat** [comment]
great, thanks for taking the time to address my question and for the excellent reference, i will try out writeroom-mode!
